-- This import creates only the BigQuery view replica requested for now.
-- Generate the exact column list from BigQuery with:
--   cd backend
--   npm run generate:vendas-consolidada-schema
--
-- Then run the generated file:
--   supabase/vw_vendas_consolidada_schema.sql
